apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: templates
  annotations:
    github.com/project-slug: snoekiede/templates
spec:
  type: other
  lifecycle: unknown
  owner: Iede Snoek

